from __future__ import annotations

import hashlib
import json
import re
import zipfile
from pathlib import Path

from lxml import etree


W_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
NS = {"w": W_NS}
PROFILE_RULES = [
    ("exp1-seqlist", ("顺序表实验", "递增有序顺序表"), 6),
    ("exp2-linklist", ("链表实验", "带头结点的单链表"), 5),
    ("exp3-stack-queue", ("栈与队列综合实验", "约瑟夫环"), 4),
    ("exp4-tree", ("二叉树与树实验", "孩子兄弟链表"), 6),
    ("exp5-graph", ("实验5 图", "无向图的类", "完成DFS算法"), 5),
]
FORBIDDEN_MARKS = (
    "AI生成",
    "由AI生成",
    "人工智能生成",
    "ChatGPT",
    "Codex",
    "大模型生成",
    "generated by ai",
    "created by ai",
)
STUDENT_DECL_BEGIN = "/*<STUDENT_DECLARATIONS_BEGIN>*/"
STUDENT_DECL_END = "/*<STUDENT_DECLARATIONS_END>*/"
STUDENT_IMPL_BEGIN = "/*<STUDENT_IMPLEMENTATION_BEGIN>*/"
STUDENT_IMPL_END = "/*<STUDENT_IMPLEMENTATION_END>*/"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def normalize_text(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def paragraph_text(element: etree._Element) -> str:
    return normalize_text("".join(element.xpath(".//w:t/text()", namespaces=NS)))


def read_docx_document_xml(path: Path) -> tuple[bytes, etree._Element]:
    with zipfile.ZipFile(path) as archive:
        data = archive.read("word/document.xml")
    return data, etree.fromstring(data)


def docx_body_paragraphs(path: Path) -> list[dict[str, object]]:
    with zipfile.ZipFile(path) as archive:
        root = etree.fromstring(archive.read("word/document.xml"))
        styles_root = etree.fromstring(archive.read("word/styles.xml"))
    style_names: dict[str, str] = {}
    for style in styles_root.findall("w:style", NS):
        style_id = style.get(f"{{{W_NS}}}styleId", "")
        name = style.find("w:name", NS)
        style_names[style_id] = name.get(f"{{{W_NS}}}val", style_id) if name is not None else style_id
    body = root.find("w:body", NS)
    if body is None:
        return []
    rows: list[dict[str, object]] = []
    for index, child in enumerate(body):
        if child.tag != f"{{{W_NS}}}p":
            continue
        style = child.find("w:pPr/w:pStyle", NS)
        rows.append(
            {
                "body_index": index,
                "text": paragraph_text(child),
                "style": style_names.get(style.get(f"{{{W_NS}}}val", ""), "") if style is not None else "",
            }
        )
    return rows


def redact_pii(text: str) -> str:
    text = re.sub(r"(?<!\d)\d{8,18}(?!\d)", "<ID>", text)
    text = re.sub(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}", "<EMAIL>", text)
    text = re.sub(r"(?<!\d)1[3-9]\d{9}(?!\d)", "<PHONE>", text)
    return text


def detect_profile(text: str) -> tuple[str | None, int | None, list[str]]:
    compact = normalize_text(text)
    matches: list[tuple[str, int, list[str]]] = []
    for profile, keywords, count in PROFILE_RULES:
        hit = [keyword for keyword in keywords if keyword in compact]
        if hit:
            matches.append((profile, count, hit))
    if not matches:
        return None, None, []
    matches.sort(key=lambda row: len(row[2]), reverse=True)
    best = matches[0]
    if len(matches) > 1 and len(matches[0][2]) == len(matches[1][2]):
        return None, None, [f"{m[0]}:{','.join(m[2])}" for m in matches]
    return best[0], best[1], best[2]


def safe_filename(value: str, fallback: str = "数据结构实验") -> str:
    value = normalize_text(value)
    value = re.sub(r"[<>:\"/\\|?*\x00-\x1f]", "-", value)
    value = value.strip(" .-")
    return value[:80] or fallback


def read_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def write_json(path: Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        json.dump(value, handle, ensure_ascii=False, indent=2)
        handle.write("\n")


def strict_gbk_decode(path: Path) -> str:
    return path.read_bytes().decode("gbk", errors="strict")


def strict_gbk_write(path: Path, text: str, crlf: bool = True) -> None:
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    if crlf:
        normalized = normalized.replace("\n", "\r\n")
    data = normalized.encode("gbk", errors="strict")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def teacher_prefix_record(path: Path) -> dict[str, object] | None:
    data = path.read_bytes()
    markers = [
        STUDENT_DECL_BEGIN.encode("gbk"),
        STUDENT_IMPL_BEGIN.encode("gbk"),
    ]
    positions = [data.find(marker) for marker in markers]
    positions = [position for position in positions if position >= 0]
    if not positions:
        return None
    length = min(positions)
    return {
        "path": str(path),
        "prefix_length": length,
        "prefix_sha256": hashlib.sha256(data[:length]).hexdigest(),
    }
